### PR TITLE
Fusion fix silo scaffolding A for real

### PR DESCRIPTION
**Pull request by Miepee**
This is how it was meant to be done

### CODE REVIEW

**Comment by JeffGainsNGames** [comment]
So what's the point of this honestly. There are no dangerous resources.

**Comment by Miepee** [comment]
Multiworlds, i.e. fusion x prime 1

**Comment by Miepee** [comment]
It also makes the solver slightly faster for higher trick levels

**Comment by JeffGainsNGames** [comment]
I understand your idea. But I'm recording that I actively think this is an unnecessary change.

**Pull request merged**
