### PR TITLE
Reservoir East Door to Escape Save Room door connection made // Pump …

### PR DESCRIPTION
**Pull request by herculesbenchpress**
…Control logic from door to missiles without speed updated to include hi-jump with a walljump trick // Security Bypass transition connected to cheddar bay door via trivial connection in security access room // Security Bypass room - Cheddar bay to security access updated to include gravity suit as a pre-req along with screw or any bombs //

### CODE REVIEW

**Review by herculesbenchpress — COMMENTED** [review]
I'm not sure why all these other sector files were added, I only added changes to sector 4.

**Comment by JeffGainsNGames** [comment]
likely some bad history. Easiest thing is a rebase. Make sure you are rebasing your branch `AQ4` with my branch `fusion`
image
image

**Comment by JeffGainsNGames** [comment]
It should say `will update AQ4 by applying it's 1 commits on top of fusion`

**Comment by herculesbenchpress** [comment]
I did rebase, but it is giving me 5 conflicting files that need to be resolved before rebase.

**Comment by herculesbenchpress** [comment]
image

**Comment by JeffGainsNGames** [comment]
I recreated these changes and added them. Sometimes easier to just remake changes on fresh branch than sorting out how to fix history/conflicts.

**Pull request closed without merging**
