### PR TITLE
More Room Name Changes

### PR DESCRIPTION
**Pull request by SchwartzGandhi**
Missile Access/Storage have been changed to Missile Mimic and Mimic Access
Aerie has been changed to Training Grounds Aerie to communicate when the check is better
Habitation Storage has been changed to Central Hub Cache to be in line Western Hub Cache
Other name changed that I forgor

### CODE REVIEW

**Comment by SchwartzGandhi** [comment]
why are there so many commits ???>:(

**Comment by JeffGainsNGames** [comment]
You seem to also have Miepee's PDF changes too

**Comment by Miepee** [comment]
IMO its better to hold off with name changes while we're still in heavy "we change logic for basically everything"-state

**Comment by JeffGainsNGames** [comment]
We'll also likely be getting rid of things like western hub so the habitation storage change is unnecessary

**Pull request closed without merging**
